name: PR Check

on:
  pull_request:

jobs:
  test-lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: package install
        run: yarn install
      - name: changeset check
        run: yarn changeset status --since origin/main
